FROM python:3.7.0-alpine3.8
MAINTAINER Martin Dulin <martin@dulin.me.uk>

RUN apk add --no-cache libpq
RUN apk add --no-cache -t .build-deps postgresql-dev gcc libc-dev

COPY docker/app/devel-entrypoint.sh /
WORKDIR /usr/src
ENTRYPOINT ["/devel-entrypoint.sh"]