FROM python:3.7.0-alpine3.8

MAINTAINER Martin Dulin <martin@dulin.me.uk>

RUN apk add --no-cache libpq
RUN apk add --no-cache -t .build-deps postgresql-dev gcc libc-dev

RUN pip install pytest tornado==5.1.1 pycryptodomex==3.6.6 psycopg2==2.7.5 aiopg==0.15.0

COPY docker/app/devel-entrypoint.sh /
WORKDIR /usr/src

ENTRYPOINT ["/devel-entrypoint.sh"]