version: '3'

services:
  postgres:
    container_name: tornado-dev-postgress
    image: postgres:9.6.10-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=tornado
      - POSTGRES_PASSWORD=tornado
      - POSTGRES_DB=tornado
      - PGDATA=/var/lib/postgresql/data/pgdata

  app:
    container_name: tornado-dev-app
    depends_on:
      - postgres
    links:
      - postgres
    restart: always
    tty: true
    build:
      context: .
      dockerfile: docker/app/Dockerfile-dev
    volumes:
      - .:/usr/src
    command: ./bin/playground --port=8080 --db_host=postgres

  nginx:
    container_name: tornado-nginx
    restart: on-failure
    build: docker/nginx
    depends_on:
      - app
    links:
      - app
    volumes:
      - ./data/cert:/cert
    ports:
      - 80:80
      - 443:443
    environment:
      - CERT_IP=192.168.99.6
      - NGINX-UID=1000
      - HTTP_PORT=80
      - HTTPS_PORT=443
      - TORNADO_WS_PORT=8080