FROM python:3.7.0-alpine3.7
MAINTAINER Martin Dulin <martin@dulin.me.uk>

RUN apk add --no-cache libpq
RUN apk add --no-cache -t .build-deps postgresql-dev gcc libc-dev

EXPOSE 8080

COPY ./scripts/devel-entrypoint.sh /
WORKDIR /usr/src
ENTRYPOINT ["/devel-entrypoint.sh"]