version: '3'

services:
  postgres:
    container_name: tornado-dev-postgress
    image: postgres:9.6.10-alpine
    volumes:
      - ./data/postgres:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_USER=tornado
      - POSTGRES_PASSWORD=tornado
      - POSTGRES_DB=tornado
      - PGDATA=/var/lib/postgresql/data/pgdata

  app:
    container_name: tornado-dev-app
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/usr/src
    links:
      - postgres
    ports:
      - 8080:8080
    command: ./bin/playground --port=8080 --db_host=postgres

